import type { ExternalImageService, ImageTransform } from 'astro'
import { generateImageUrl } from '@imgproxy/imgproxy-node'
import { baseService } from 'astro/assets'
import { readFile } from 'node:fs/promises'
import { resolve } from 'node:path'

// Last-resort fallback when imageConfig.service.config.sizes is not set.
// Configure via astro.config.ts: image.service.config.sizes
const DEFAULT_SIZES = [640, 750, 828, 1080, 1200, 1920, 2048, 3840] as const

// Astro uses 'jpeg'; imgproxy uses 'jpg' — normalise here.
type ImgproxyFormat = 'avif' | 'webp' | 'png' | 'jpg'

interface ImageMeta {
  width: number
  height: number
  blurhash: string
}

function toImgproxyFormat(format: string | undefined): ImgproxyFormat {
  if (format === 'jpeg') {
    return 'jpg'
  }
  if (
    format === 'avif' ||
    format === 'webp' ||
    format === 'png' ||
    format === 'jpg'
  ) {
    return format
  }
  return 'webp'
}

function isLocalMode(): boolean {
  return (
    import.meta.env.PUBLIC_IMAGE_MODE !== 'imgproxy' ||
    !import.meta.env.IMGPROXY_ENDPOINT
  )
}

// Cached metadata per project — loaded once from metadata.json at build time.
const metadataCache = new Map<string, Record<string, ImageMeta>>()

// Blurhash per src — populated in validateOptions, consumed in getHTMLAttributes.
const blurhashMap = new Map<string, string>()

// src format: "projects/{project}/images/{filename}"
async function readLocalMeta(src: string): Promise<ImageMeta | undefined> {
  const parts = src.split('/')
  if (parts.length < 4 || parts[0] !== 'projects') {
    return undefined
  }
  const project = parts[1]
  const filename = parts.at(-1)!

  if (!metadataCache.has(project)) {
    const metaPath = resolve(
      process.cwd(),
      'content',
      'projects',
      project,
      'metadata.json',
    )
    try {
      const data = JSON.parse(await readFile(metaPath, 'utf8'))
      metadataCache.set(project, data)
    } catch {
      // metadata.json missing — run `pnpm images:meta` to generate it
      metadataCache.set(project, {})
    }
  }

  return metadataCache.get(project)?.[filename]
}

const service: ExternalImageService = {
  // baseService.validateOptions calls verifyOptions() which rejects src strings that
  // are not remote URLs or don't start with '/'. Our src is an internal path like
  // "projects/atom/images/01.jpg", so we implement only the relevant subset:
  //   — widths + densities together → error (incompatible descriptors)
  //   — set format default (webp) when omitted
  //   — round width/height to integers
  //   — read width/height/blurhash from metadata.json (generated by images:meta)
  async validateOptions(options: ImageTransform): Promise<ImageTransform> {
    if (options.widths && options.densities) {
      throw new Error(
        'Cannot use both `widths` and `densities` on the same image.',
      )
    }
    if (typeof options.src === 'string') {
      const meta = await readLocalMeta(options.src)
      if (meta) {
        blurhashMap.set(options.src, meta.blurhash)
        if (!options.width && !options.height) {
          options.width = meta.width
          options.height = meta.height
        } else if (options.width && !options.height) {
          options.height = Math.round(
            (options.width * meta.height) / meta.width,
          )
        }
      }
    }
    return {
      ...options,
      format: options.format ?? 'webp',
      width:
        options.width === undefined ? undefined : Math.round(options.width),
      height:
        options.height === undefined ? undefined : Math.round(options.height),
    }
  },

  // Extends baseService to pass data-blurhash through to the <img> element.
  async getHTMLAttributes(options, imageConfig) {
    const attrs = await baseService.getHTMLAttributes!(options, imageConfig)
    const src = typeof options.src === 'string' ? options.src : ''
    const bh = blurhashMap.get(src)
    if (bh) {
      attrs['data-blurhash'] = bh
    }
    return attrs
  },

  // options.src is a path string: "projects/{project}/images/{filename}"
  getURL(options) {
    const src = typeof options.src === 'string' ? options.src : options.src.src
    const width = options.width ?? 1920
    const format = toImgproxyFormat(options.format)

    if (isLocalMode()) {
      // Dev: /img/[...path].ts serves originals from disk — no resize needed.
      return `/img/${src}`
    }

    return generateImageUrl({
      endpoint: import.meta.env.IMGPROXY_ENDPOINT,
      key: import.meta.env.IMGPROXY_KEY,
      salt: import.meta.env.IMGPROXY_SALT,
      url: `s3://${import.meta.env.S3_BUCKET}/${src}`,
      options: {
        resize: { width, height: 0, resizing_type: 'fill' },
        format,
      },
    })
  },

  getSrcSet(options, imageConfig) {
    // Local mode: /img/ serves the original file at any "size" — srcset would
    // produce identical URLs with different descriptors, which is pointless.
    if (isLocalMode()) {
      return []
    }

    const { widths, densities } = options

    // densities: e.g. <Image densities={[1, 2, 3]} /> → 1x 2x 3x descriptors
    if (densities) {
      const base = options.width ?? 1920
      const parsed = densities
        .map(d => (typeof d === 'number' ? d : Number.parseFloat(d)))
        .toSorted((a, b) => a - b)
      return parsed.map(d => ({
        transform: { ...options, width: Math.round(base * d) },
        descriptor: `${d}x`,
      }))
    }

    // widths: e.g. <Image widths={[400, 800, 1200]} /> → 400w 800w 1200w descriptors
    // fallback: configured sizes, then built-in defaults
    const configSizes = imageConfig.service.config?.sizes
    const fallback: number[] = Array.isArray(configSizes)
      ? configSizes
      : [...DEFAULT_SIZES]
    const resolvedWidths: number[] = widths?.length
      ? widths.toSorted((a, b) => a - b)
      : fallback

    return resolvedWidths.map(w => ({
      transform: { ...options, width: w },
      descriptor: `${w}w`,
    }))
  },
}

export function buildImageUrl(path: string, width = 1920): string {
  if (isLocalMode() || import.meta.env.DEV) {
    return `/img/${path}`
  }
  return generateImageUrl({
    endpoint: import.meta.env.IMGPROXY_ENDPOINT,
    key: import.meta.env.IMGPROXY_KEY,
    salt: import.meta.env.IMGPROXY_SALT,
    url: `s3://${import.meta.env.S3_BUCKET}/${path}`,
    options: {
      resize: { width, height: 0, resizing_type: 'fill' },
      format: 'webp',
    },
  })
}

export default service
