catalog:
  '@astrojs/check': ^0.9.9
  '@csstools/postcss-global-data': ^4.0.0
  '@types/node': ^25.6.0
  astro: ^6.2.1
  nano-staged: ^1.0.2
  oxc-config-fans: ^0.0.4
  oxfmt: ^0.47.0
  oxlint: ^1.62.0
  postcss-custom-media: ^12.0.1
  simple-git-hooks: ^2.13.1
  typescript: ^6.0.3
  wrangler: ^4.87.0

onlyBuiltDependencies:
  - esbuild
  - sharp
  - simple-git-hooks
  - unrs-resolver
